---
input_timesteps: 960
output_timesteps: 480
batch_size: 64
max_epochs: 10000
patience: 50
train_data:
  - [./data/train_x1.wav, ./data/train_y1.wav]
  - [./data/train_x2.wav, ./data/train_y2.wav]
  - [./data/train_x3.wav, ./data/train_y3.wav]
val_data:
  - [./data/val_x.wav, ./data/val_y.wav]
